# Generated by Django 3.2.9 on 2021-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('начальный', 'easy'), ('средний', 'medium'), ('продвинутый', 'hard')], max_length=11),
        ),
    ]
